openapi: 3.0.3
info:
  title: Music info
  version: 0.0.1
servers:
- url: /
paths:
  /info:
    get:
      parameters:
      - explode: true
        in: query
        name: group
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: song
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetail'
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    SongDetail:
      example:
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        text: Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou
          caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou
          set my soul alight\nOoh\nYou set my soul alight
      properties:
        releaseDate:
          example: 16.07.2006
          type: string
        text:
          example: Ooh baby, don't you know I suffer?\nOoh baby, can you hear me moan?\nYou
            caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou
            set my soul alight\nOoh\nYou set my soul alight
          type: string
        link:
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
          type: string
      required:
      - link
      - releaseDate
      - text
      type: object
